### ISSUE TITLE
Missing $ inserted

### ISSUE THREAD

**Issue by ildar** [davidcarlisle/latexcgi#13]
Running simply the curl script
> $ sh ../tldnet formulae.tex

The TexLive.net seems not tolerate newlines after `\[` and before `\]`.
My local TexLive 2021 processes the same file just fine. Any idea why?
File:
```latex
\documentclass{article}
\begin{document}
test

\[
\alpha
\]
\end{document}
```

**Comment by ildar** [comment]
BTW it is LyX puts newline after `\[`

**Comment by davidcarlisle** [comment]
that's a bit weird, but I can reproduce, so I'll try and find time over the holidays to see what it's doing
