### ISSUE TITLE
Add `makeglossaries` to `% !TEX  ... keyword`

### ISSUE THREAD

**Issue by dbitouze** [davidcarlisle/latexcgi#14]
It would be nice to add `makeglossaries` to the list of the [known keywords for `% !TEX  ... keyword`](https://davidcarlisle.github.io/latexcgi/#the-learnlatex-comment-interface-runlatexjs).

**Comment by davidcarlisle** [comment]
I guess so, although you can usually use makeindex with suitable options. I'll see what I can do...

**Comment by davidcarlisle** [comment]
mostly it would work by using 

```
% !tex   makeindex -s document.ist -t document.glg -o document.gls document.glo
```

but  I have added a `makeglossaries` parameter to the latexgi form with allowed values `makeglossaries` and `makeglossaries-light`  also those are added as keywords for the `% !TeX` comments, so...


https://texlive.net/run?%25%20!tex%20makeglossaries%0A%5Cdocumentclass%7Barticle%7D%0A%0A%5Cusepackage%7Bglossaries-extra%7D%0A%0A%5Cmakeglossaries%0A%0A%5Cnewglossaryentry%7Bfoo%7D%7Bname=foo,description=%7Ban%20example%7D%7D%0A%5Cnewglossaryentry%7Bbar%7D%7Bname=bar,description=%7Banother%20%0Aexample%7D,see=%7Bfoo%7D%7D%0A%0A%5Cbegin%7Bdocument%7D%0A%5Cgls%7Bbar%7D.%0A%0A%5Cprintglossaries%0A%0A%5Cend%7Bdocument%7D
