### ISSUE TITLE
[FR] documents with pictures

### ISSUE THREAD

**Issue by ildar** [davidcarlisle/latexcgi#16]
allow to process documents with pictures (as separate files)

**Comment by davidcarlisle** [comment]
You can include images if using this on a server you control, eg

macbeth here
https://davidcarlisle.github.io/latexcgi/test2#scottish-play

or  images already in texlive eg graphics lesson at learnlatex

https://www.learnlatex.org/en/lesson-07

what I don't currently support is using the multifile upload for anything other than text.

It would be possible of couse but supporting binary uploads complicates the form processing and increases the security concerns. 

The service is already offering a free compute resourse at no cost or login.  
At some point you really want to defer to services like overleaf that have user accounts, so much more traceability.

Some image formats of course you can upload as text, notably EPS.

So...  it's not an unreasonable request, but I have no plans to do this currently.

**Comment by ildar** [comment]
Thanks a lot for the clarification. And thank you for the free LaTeX
compiler on the web.
👍
