### ISSUE TITLE
`pdfTeX error: pdflatex (file fcr14): Font fcr14 at 600 not found`

### ISSUE THREAD

**Issue by dbitouze** [davidcarlisle/latexcgi#23]
The following code:

```latex
\documentclass{article}
\usepackage[T4]{fontenc}
\begin{document}
\Large
\G{A} \G{B} \G{C} \G{D} \G{E} \G{F} \G{G} \G{H} \G{I} \G{J} \G{K} \G{L} \G{M}

\G{N} \G{O} \G{P} \G{Q} \G{R} \G{S} \G{T} \G{U} \G{V} \G{W} \G{X} \G{Y} \G{Z} 

\G{\OE} \G{\AE} \G{\O}

\G{a} \G{b} \G{c} \G{d} \G{e} \G{f} \G{g} \G{h} \G{\i} \G{\j} \G{k} \G{l} \G{m}
\G{n} \G{o} \G{p} \G{q} \G{r} \G{s} \G{t} \G{u} \G{v} \G{w} \G{x} \G{y} \G{z} 

\G{\oe} \G{\ae} \G{\o}
\end{document}
```
doesn't compile via `latexcgi` because of:
```
pdfTeX error: pdflatex (file fcr14): Font fcr14 at 600 not found
 ==> Fatal error occurred, no output PDF file produced!
```
Is it hopeless?

**Comment by davidcarlisle** [comment]
not sure why it didn't build, I'll check later but it's there now

https://davidcarlisle.github.io/latexcgi/run?%0A%5Cdocumentclass%7Barticle%7D%0A%5Cusepackage%5BT4%5D%7Bfontenc%7D%0A%5Cbegin%7Bdocument%7D%0A%5CLarge%0A%5CG%7BA%7D%20%5CG%7BB%7D%20%5CG%7BC%7D%20%5CG%7BD%7D%20%5CG%7BE%7D%20%5CG%7BF%7D%20%5CG%7BG%7D%20%5CG%7BH%7D%20%5CG%7BI%7D%20%5CG%7BJ%7D%20%5CG%7BK%7D%20%5CG%7BL%7D%20%5CG%7BM%7D%0A%0A%5CG%7BN%7D%20%5CG%7BO%7D%20%5CG%7BP%7D%20%5CG%7BQ%7D%20%5CG%7BR%7D%20%5CG%7BS%7D%20%5CG%7BT%7D%20%5CG%7BU%7D%20%5CG%7BV%7D%20%5CG%7BW%7D%20%5CG%7BX%7D%20%5CG%7BY%7D%20%5CG%7BZ%7D%20%0A%0A%5CG%7B%5COE%7D%20%5CG%7B%5CAE%7D%20%5CG%7B%5CO%7D%0A%0A%5CG%7Ba%7D%20%5CG%7Bb%7D%20%5CG%7Bc%7D%20%5CG%7Bd%7D%20%5CG%7Be%7D%20%5CG%7Bf%7D%20%5CG%7Bg%7D%20%5CG%7Bh%7D%20%5CG%7B%5Ci%7D%20%5CG%7B%5Cj%7D%20%5CG%7Bk%7D%20%5CG%7Bl%7D%20%5CG%7Bm%7D%0A%5CG%7Bn%7D%20%5CG%7Bo%7D%20%5CG%7Bp%7D%20%5CG%7Bq%7D%20%5CG%7Br%7D%20%5CG%7Bs%7D%20%5CG%7Bt%7D%20%5CG%7Bu%7D%20%5CG%7Bv%7D%20%5CG%7Bw%7D%20%5CG%7Bx%7D%20%5CG%7By%7D%20%5CG%7Bz%7D%20%0A%0A%5CG%7B%5Coe%7D%20%5CG%7B%5Cae%7D%20%5CG%7B%5Co%7D%0A%5Cend%7Bdocument%7D

(I just ran the file on the server and the fonts built)

**Comment by dbitouze** [comment]
Indeed, looks okay now: thanks! (I'm not sure whether I should close this issue or not.)

**Comment by davidcarlisle** [comment]
leave open and I'll look later why it failed: I think the security blocking of some directories is over-eager

**Comment by davidcarlisle** [comment]
OK the issue was that 
TEXMFVAR had the default value under the home directory but the server runs in an account without a home directory but it does own the texlive installation so I have set (in `texlive/2024/texmf.cnf`)

% dont use home var
TEXMFVAR = $TEXMFROOT/texmf-var

so TEXMFVAR is the same as TEXMFSYSVAR and the files do now get rebuilt (after I deleted them) in
`/usr/local/texlive/2024/texmf-var/fonts/pk/ljfour/jknappen/fc/`
