### ISSUE TITLE
xelatex engine didn't return pdf

### ISSUE THREAD

**Issue by saffiullahfahim** [davidcarlisle/latexcgi#5]
I try this but every time get log not pdf!
```
%!TEX xelatex
\documentclass[50pt,a5paper,english]{article}
\usepackage[T1]{fontenc}
\usepackage{fontspec} 
\newfontfamily\ben{Kalpurush}
\usepackage{babel}
\usepackage{geometry}
\usepackage{blindtext}

\title{A5 paper size}
\author{kostas}

\begin{document}
  \maketitle
{\ben কম্পিউটার বিজ্ঞান} 
\end{document}
```

**Comment by davidcarlisle** [comment]
hmm it works with lualatex, but with xelatex  the log shows tex compling without error but then it times out. I have a timeout for security reasons, but it should have enough time here, I'll see if I can see what is taking the time....

**Comment by saffiullahfahim** [comment]
It is also show Timeout/Error status: 124 [xelatex][document].
```
%!TEX xelatex
  \documentclass{article}
  \usepackage{iftex}
  \newcommand\test[1]{\par\expandafter#1\string#1: true\fi}
  \begin{document}
  \ttfamily
  \test\ifpdftex
  \test\ifluatex
  \test\ifxetex
  \test\ifptex
  \test\ifuptex
  \end{document}
```

**Comment by davidcarlisle** [comment]
https://texlive.net/run?%0A%25!TEX%20xelatex%0A%5Cdocumentclass%5B50pt,a5paper,english%5D%7Barticle%7D%0A%0A%5Cusepackage%5BT1%5D%7Bfontenc%7D%0A%0A%5Cusepackage%7Bfontspec%7D%20%0A%0A%5Cnewfontfamily%5Cben%7BKalpurush%7D%0A%0A%5Cusepackage%7Bbabel%7D%0A%0A%5Cusepackage%7Bgeometry%7D%0A%0A%5Cusepackage%7Bblindtext%7D%0A%0A%0A%0A%5Ctitle%7BA5%20paper%20size%7D%0A%0A%5Cauthor%7Bkostas%7D%0A%0A%0A%0A%5Cbegin%7Bdocument%7D%0A%0A%20%20%5Cmaketitle%0A%0A%7B%5Cben%20%E0%A6%95%E0%A6%AE%E0%A7%8D%E0%A6%AA%E0%A6%BF%E0%A6%89%E0%A6%9F%E0%A6%BE%E0%A6%B0%20%E0%A6%AC%E0%A6%BF%E0%A6%9C%E0%A7%8D%E0%A6%9E%E0%A6%BE%E0%A6%A8%7D%20%0A%0A%5Cend%7Bdocument%7D%0A%0A

works for me now (it was slow first time, after updating to texlive 2022)

**Comment by saffiullahfahim** [comment]
Yeah! It works perfectly. Thank you for fixed this!
